# Generated by Django 3.0.6 on 2020-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200514_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='destination',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
