# Generated by Django 3.0.6 on 2020-05-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200514_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
