# Generated by Django 3.0.6 on 2020-05-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200514_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_short_form', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentShiftInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='address',
            field=models.CharField(default='Madinah', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='father_name',
            field=models.CharField(default='Zahid', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='roll',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_section', models.CharField(max_length=50)),
                ('std_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentClassInfo')),
                ('std_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentShiftInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo')),
            ],
        ),
    ]
